name = "ocr-pro-react"
compatibility_date = "2024-11-20"
pages_build_output_dir = "./dist"

# Enable Node.js compatibility for Pages Functions utilities
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"            # Accessible via env.DB inside Pages Functions
# Update these with `wrangler d1 create` results before deploying
# Example: wrangler d1 create ocrpro-db
# Then paste the generated database_id below
# database_name is informative for wrangler; it's fine to reuse the created name
# Replace the placeholders once you have the actual values
# These placeholders keep the repo committed while signalling required action
# DO NOT DEPLOY until database_id is filled in.
database_name = "ocrpro-db"
database_id = "5f16e784-85fc-4dc7-b1ee-34eb91074d5b"
