name = "ocr-pro-react"
compatibility_date = "2024-11-20"
pages_build_output_dir = "./dist"

# Enable Node.js compatibility for Pages Functions utilities
compatibility_flags = ["nodejs_compat"]

# Environment variables for authentication
[vars]
JWT_SECRET = "your_jwt_secret_here"
FIREBASE_ADMIN_PROJECT_ID = "your_project_id"
FIREBASE_ADMIN_CLIENT_EMAIL = "your_service_account_email"
# Note: FIREBASE_ADMIN_PRIVATE_KEY should be set as a secret, not in vars

[[d1_databases]]
binding = "DB"            # Accessible via env.DB inside Pages Functions
database_name = "ocrpro-db"
database_id = "5f16e784-85fc-4dc7-b1ee-34eb91074d5b"
migrations_dir = "migrations"
