name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  # Remove pull_request trigger to prevent unnecessary deployments

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    # Only deploy on main branch pushes
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          VITE_GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY }}
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_FIREBASE_CONFIG: ${{ secrets.VITE_FIREBASE_CONFIG }}

      - name: Verify Cloudflare Configuration
        run: |
          echo "Account ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
          echo "Project: ocr-pro-react"
          echo "Build directory: dist"
          ls -la dist/ || echo "Dist directory not found"

      - name: Deploy to Cloudflare Pages
        run: |
          echo "Starting deployment..."
          npx wrangler pages deploy dist --project-name=ocr-pro-react
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deployment Status
        if: always()
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Deployment failed!"
            echo "Check logs above for details"
          fi